/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { draco, Shadow } from 'drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/geo-d.glb', draco())
  useFrame(() => (group.current.rotation.x = group.current.rotation.z += 0.005))
  return (
    <group {...props} dispose={null}>
      <group ref={group}>
      <mesh geometry={nodes.geo.geometry} castShadow receiveShadow>
          <meshPhysicalMaterial color="white" roughness={1} metalness={0.5}/>
        </mesh>
      </group>
      <Shadow opacity={0.6} rotation-x={-Math.PI / 2} position={[0, -1.51, -1]} scale={[2, 2, 2]} />
    </group>
  )
}
